### ISSUE TITLE
[Bug] Not paste User/Repository into Browser

### ISSUE THREAD

**Issue by Kristinita** [divinites/gissues#58] opened 2016-10-06 07:12 UTC
### Summary

I can not paste `User/Repository` name, when I copy `User/Repository` into my browser — Firefox. When I copy `User/Repository` into Sublime Text, paste is good.
### Expected behavior

Successful paste `User/Repository` into browser.
### Actual behavior

![GIssues Paste](http://i.imgur.com/VmoyGEg.gif)
### Steps to reproduce

`GitHub Issues: Create Issue` → manually enter repository... → I copy `User/Repository` into browser → I paste `User/Repository` to text area → I don't saw paste result.
### Environment

**Operating system and version:**
Windows 10.0.14393
**Sublime Text:**
Build 3126
**Firefox:**
Portable 49.0.1

Thanks.

**Comment by divinites** [comment] 2016-10-06 07:57
I cannot replicate this error at this moment. I tested Chrome, Internet Explorer and Edge, none of these browsers has this problem. I will download a Firefox to test if it works. In the mean time, could you plese tell if your <kbd>ctrl</kbd> + <<kbd>v</kbd> could really pick up the content from the firefox browser, i.e. you can try to paste the content to Sublime Text's main view.

**Comment by Kristinita** [comment] 2016-10-06 08:10
@divinites , reproduce on new [FirefoxPortable](http://portableapps.com/apps/internet/firefox_portable) for me. If I paste same text into text, command palette or find console in Sublime Text, paste is good.

Not reproduce in Chrome and Opera. In that browsers I can paste normally.

Thanks.

**Comment by divinites** [comment] 2016-10-06 08:59
@Kristinita  I downloaded a Firefox in Windows and copy/paste seems fine for me. I believe this is not a bug of this plug-in. It might be a subtle problem of Sublime Text itself or a bug of firefox and some of its plug-ins.

**Comment by Kristinita** [comment] 2016-10-08 16:43
I don't happy that you have put a label `wontfix`. You can lose Firefox users, who may also be copied character `\n`.

![GitHub Issues 404](http://i.imgur.com/XmHicyt.gif)

Line to debugging log in console:

```
INFO:GitHubIssue:repo_info_storage contains ('\ndivinites', 'gissues\n', None)
```

I propose automatically delete the characters `\n`, if `\n` are inserted.

Thanks.

**Comment by divinites** [comment] 2016-10-08 16:50
Wow, I put a "wontfix" because I thought it was a bug of firefox or sublime text itself. But fortunately, you pointed out that it was an issue of '\n'. I won't disappoint you and I will fix it today.

**Comment by divinites** [comment] 2016-10-08 17:30
@Kristinita Since I cannot reproduce this problem, Could I rely on you to test the new release 1.6.2? It is supposed to solve this issue you raised, I just pushed it to the master branch.

If you copy/paste before `Enter repo in the format...`, you will be able to see that "name/repo_name". If you copy/paste after this prompt, you will not be able to see what you paste, but you still can successfully open the repo.

**Comment by Kristinita** [comment] 2016-10-08 17:58
Thanks! This problem seems to be solved, but there is a new: `KeyError: 'label'`. I create issue for you:

``` markdown
# Title         : 404?
## Assignee     : 
*----------Content----------*
None!
*----------END----------*
```

I post issue and I get stack trace:

``` python
command: post_github_issue {}
INFO:GitHubIssue:try to find the view in repo_dictionary...
INFO:GitHubIssue:repo_info_storage contains ('divinites', 'gissues', None)
INFO:GitHubIssue:curcial line is {'comment_start': [], 'end': 4, 'comment_end': [], 'header_end': 2, 'add_comment': 0}
INFO:GitHubIssue:issue_header is {'Title': '404?', 'Assignee': ''}
Exception in thread Thread-113:
Traceback (most recent call last):
  File "./python3.3/threading.py", line 901, in _bootstrap_inner
  File "libgit.issue in E:\Sublime Text 3\Data\Installed Packages\GitHubIssue.sublime-package", line 286, in run
  File "libgit.utils in E:\Sublime Text 3\Data\Installed Packages\GitHubIssue.sublime-package", line 242, in get_issue_post
KeyError: 'label'
```

**Comment by divinites** [comment] 2016-10-08 18:01
ah, I know this problem, because I am adding label support, but I forgot adding it in the creating issue framework, I will fix it now.

**Comment by divinites** [comment] 2016-10-08 19:35
The new release 1.6.9 solved this problem, and with full label support! see update message for details

**Closed as completed** 2016-10-09 10:06 UTC
Labels: bug, presumely solved
